# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Triggers the workflow on issues
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

    auto-assign:

        runs-on: ubuntu-latest

        steps:

            - name: 'Auto-assign issue'

              uses: pozil/auto-assign-issue@v1.13.0

              with:
              
                  assignees: thelo67

                  
